### ISSUE TITLE
change reading data model

### ISSUE THREAD

**Issue by andyczerwonka** [andyczerwonka/tyrion#131]
There are some consequences to our internal data model that make some use cases extremely difficult and in some cases impossible.

We need to change the data model of support the following:

1. sparse sensor configuration, e.g. deploy a box configured with only two sensors, positions 2 & 5
2. add sensors, remove sensors

The idea is to give the model more context when the reading comes in so that it can exist in isolation to changes in the sensor configuration. 

### Tasks

- [x] core data model
- [x] update script
- [x] admin UI
- [x] site history
- [x] sensor status

**Comment by andyczerwonka** [comment]
I need to write a migration script for all the sensors.

**Comment by andyczerwonka** [comment]
![selection_604](https://cloud.githubusercontent.com/assets/138898/9977546/443a4910-5ec9-11e5-91ed-a5ec6925d5c9.png)

**Comment by mbrigdan** [comment]
Hey Andy, are there going to be changes you need me to make on my end to support this? Let me know and I can get them started.

**Comment by andyczerwonka** [comment]
The change will be transparent to you. You will still send me an ordered array as before, I will coalesce with the site configuration and store only the configured sensors. I will let you guys know the implications once this change is in place. We will be dropping all readings as part of this migration.

**Comment by andyczerwonka** [comment]
This change is complete and needs more testing. I have been testing it in a branch for a couple of hours. Before I merge this change into the main tree, let's discuss implications with the upgrade.

**Comment by andyczerwonka** [comment]
From the `database` directory, run `mongo tyrion 131_add_sensor_slot.js`. That's assuming the database name is `tyrion`. This will *clear all readings to date" as well as add the slot numbers starting at index 1.
