### ISSUE TITLE
site-level logs

### ISSUE THREAD

**Issue by andyczerwonka** [andyczerwonka/tyrion#135]
There are exceptional situations where the site may not function properly, due to:

1. network is down
2. sensors are not returning any values
3. camera is not responding
4. etc (other unforeseen issues)

Admins need an ability to see this data to help with technical triage.

We should instrument the code (it already is in most cases) to log exceptions. We will add a new message type to the current instruction protocol (currently only `reading` and `image`) that requests all log messages. The site will post the logs to a new endpoint and delete them locally after a successful post.

There is a client and server footprint for this functionality.

**Comment by andyczerwonka** [comment]
## Client Logs API

There will be a new message added to the current command API.

```
reading
image
sleep
logs
```

The client will unconditionally log all error states. When it receives a `logs` message, the client will send all logs. After a successful `200 OK` message, the client will delete all logs.

`HTTP POST to /api/logs`

### Payload

We'll expect an array of tuples, where each tuple is:
1. an ISO-formatted date string and
2. an error message

```json
[
  ["2015-07-16T19:20:39-06:00", "This is an error message"]
  ["2015-07-16T19:20:41-06:00", "This is another error message"]
]
```

**Comment by mbrigdan** [comment]
I've implemented the functionality in my client. One thing to clarify, if there's no logs to send, do you want the client not to send anything, or to still connect to the end point and send an empty message / empty array.

**Comment by andyczerwonka** [comment]
If there's nothing to send, don't do anything.

**Comment by andyczerwonka** [comment]
![exterra monitoring - google chrome_604](https://cloud.githubusercontent.com/assets/138898/9837741/60bc9a9c-5a06-11e5-90ac-a8512ad900fa.png)

**Comment by andyczerwonka** [comment]
@mbrigdan This feature is done, go ahead and run it locally for a while so that we can see what kind of logs we're getting. cc: @laurentbrig
