### ISSUE TITLE
Possibly changing from clients staying on by default to staying off

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#143]
After switching the hardware between site 7-4 and 5-29, we've seen the problem with a site going down resolve. My best guess about what is going on is that a temporary connection issue is causing the modem driver to stop trying to connect, and the old hardware that automatically restarts is avoiding this problem. 

Changing the default behaviour of the client to turn off unless they are told to turn on should solve this problem, as well as saving battery on the clients.

What do you think @andyczerwonka ?

**Comment by andyczerwonka** [comment]
Right now we send a sleep message, are you suggesting you unconditionally sleep just to always have a fresh boot up?

**Comment by laurentbrig** [comment]
We should discuss the pros / cons.
Forced reboots seems to mask problems but saves truck rolls so it's double
edged

**Comment by andyczerwonka** [comment]
Closing this issue, we have made the change.
