### ISSUE TITLE
"logs" action is after "sleep" in the returned array

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#146]
The array returned from the site has the logs action last, because the client executes actions in order, it will go to sleep before sending logs.

**Comment by andyczerwonka** [comment]
@mbrigdan good find. Initially thinking of a simple fix, but as a more general solution I'm going to introduce the notion of priority in the model. The priorities will allow us to encode order dependencies, essentially giving order to the command queue.
