### ISSUE TITLE
Dashboard tiling when images are of different resolution

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#84]
![image](https://cloud.githubusercontent.com/assets/11862839/7058662/56d02978-de22-11e4-9876-fa18410ea056.png)

Differently sized images throw off the tiling pattern of the dashboard. The second row of images should be fully beneath the first row.

**Comment by andyczerwonka** [comment]
@mbrigdan what is the aspect ratio of the image in the camera you are using?

**Comment by mbrigdan** [comment]
640x480, which is 4:3

**Comment by andyczerwonka** [comment]
I've removed all the fake sites, so this will not be a problem for now. It's still an issue, it just won't manifest.
