### ISSUE TITLE
HTTP Error 413 in response to image POST

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#87]
The server is returning an HTTP Error 413 (Request entity too large) in response to image POSTs.

It looks like there's a certain limit on the size of requests, and larger images are hitting it. I think the solution is to just increase that limit, possibly to around 500K or so?

**Comment by andyczerwonka** [comment]
@mbrigdan you can now upload pictures up to 1M.

**Comment by mbrigdan** [comment]
@andyczerwonka The site is still returning a 413 response to images. Are you sure
5432ea7
```
maxLength = 1024 * 10
```
sets it to 10M?

**Comment by andyczerwonka** [comment]
Oops... that's 10k, that clearly won't do it.
