### ISSUE TITLE
Site commands should be updated more frequently

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#88]
At the moment, site commands appear to be updated every ~5 minutes. When the board is shutting down for a similar length of time, there's timings where the site command isn't updated in time, ending up with a "missed" reading where you have a 9-11 minute gap instead of a 5 minute gap.

Solution: Update site commands more frequently (q 1 minute ~ q 30s)

**Comment by andyczerwonka** [comment]
These are now updated every 30 seconds. This will eventually become a site specific setting.
